version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'saturday'
      time: '06:00'
      timezone: 'Europe/Paris'
    target-branch: 'develop'
    open-pull-requests-limit: 10
    ignore:
      - dependency_name: 'react'
      - dependency_name: '@types/react'
      - dependency_name: 'react-native'
      - dependency_name: '@types/react-native'
      - dependency_name: 'metro-react-native-babel-preset'
      - dependency_name: 'react-dom'
      - dependency_name: '@storybook/*'
      - dependency_name: 'babel-jest'
      - dependency_name: 'jest'
      - dependency_name: 'jest-circus'
      - dependency_name: 'ts-jest'
      - dependency_name: '@types/jest'
